name: Build and test pawn

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    strategy:
      matrix:
        config:
          - name: "Ubuntu Latest - GCC"
            os: ubuntu-latest
            cc: gcc
            cxx: g++
          - name: "Ubuntu Latest - Clang"
            os: ubuntu-latest
            cc: clang
            cxx: clang++
          - name: "Ubuntu 20.04 - GCC"
            os: ubuntu-20.04
            cc: gcc
            cxx: g++
          - name: "Ubuntu 20.04 - Clang"
            os: ubuntu-20.04
            cc: clang
            cxx: clang++
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract bench signature
        run: "git log HEAD | grep 'Bench: ' | head -n 1 | awk '{print $2}' > bench.sig"
      - name: Build pawn
        run: "make"
      - name: Run bench
        run: "build/pawn bench 2>&1 | grep 'Nodes searched:' | awk '{print $3}' > bench.out"
      - name: Verify bench signature
        run: "cmp bench.sig bench.out"
      - name: Run tests
        run: "build/pawn test | grep -q 'All tests passed'"
